apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matching-platform.fullname" . }}-matching-engine
  labels:
    app: matching-engine
spec:
  replicas: {{ .Values.matchingEngine.replicaCount }}
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
        - name: matching-engine
          image: "{{ .Values.image.repository }}/matching-engine:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.matchingEngine.port }}
              protocol: TCP
            - name: telemetry
              containerPort: {{ .Values.matchingEngine.telemetryPort }}
              protocol: TCP
          args:
            - "--port"
            - "{{ .Values.matchingEngine.port }}"
            - "--telemetry-port"
            - ":{{ .Values.matchingEngine.telemetryPort }}"
          resources:
            {{- toYaml .Values.matchingEngine.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matching-platform.fullname" . }}-matching-engine
  labels:
    app: matching-engine
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.matchingEngine.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.matchingEngine.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
      name: telemetry
  selector:
    app: matching-engine
